### ISSUE TITLE
Итератор для значения не определен

### ISSUE THREAD

**Issue by ChernyakAI** [SeiOkami/RegularExpressionOneS#2]
Воспроизведение проблемы:
1. Первое открытие обработки или её открытие после чистки настроек формы в хранилище настроек.
2. Задать регулярное выражение и тестовую строку
3. Выбрать действие замера "Поиск" и указать количество подходов. Количество за подход не указывать (оставляем = 0).
4. Нажать "Выполнить замеры".
В итоге, переменные РезультатМетода, ТекущийРезультат в методах поиска (например, ВыполнитьЗамер_Поиск_Платформенный) остаются неинициализированными.

**Comment by SeiOkami** [comment]
Спасибо, исправил в рамках релиза [v0.1.2](https://github.com/SeiOkami/RegularExpressionOneS/releases/tag/v0.1.2)
